#
# Copyright (c) 2013, 2014 by Lifted Studios. All Rights Reserved.
#

AllCops:
  Excludes:
    - bin/*    # Temporary until finish refactoring everything out of bin/lush

LineLength:
  Enabled: true
  Max: 100

SignalException:
  Enabled: true
  EnforcedStyle: only_raise
